# Site settings
title: Is Shell Command ______ Portable?
email: mail@michael.kropat.name
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/is-shell-portable" # the subpath of your site, e.g. /blog/
url: "http://mkropat.github.io" # the base hostname & protocol for your site
twitter_username: MichaelKropat
github_username:  mkropat

# Build settings
markdown: kramdown
